service: miranda-backend
frameworkVersion: "3"
package:
  patterns:
    - "!./**"
    - "package.json"
    - "node_modules/**"
    - "dist/**"
provider:
  name: aws
  region: eu-west-1
  environment:
    SECRET: ${file(.env.json):TOKEN_SECRET}
  runtime: nodejs18.x
functions:
  app:
    handler: dist/lambda.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}